title: Teoría de Algoritmos I
description: >
  Página de la materia Teoría de Algoritmos I. Facultad de Ingeniería,
  Universidad de Buenos Aires.
baseurl: "/tda"
url: "https://algoritmos-rw.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
markdown: kramdown
permalink: pretty

# XXX Remove
header_pages:
  - /none

kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"

exclude: ["Gemfile"]
